### ISSUE TITLE
R Packages for Biochemistry

### ISSUE THREAD

**Issue by discoleo** [cran-task-views/ChemPhys#16]
Various R packages are not included in the Task View:
- First 2 are general packages;
- Packages 3 - 7 use various statistical models to predict certain features/proteins;
- Remaining: other functions;

1. Package Peptides: https://cran.r-project.org/web/packages/Peptides/index.html
2. Package [seqinr](https://cran.r-project.org/web/packages/seqinr/index.html): Biological Sequences Retrieval and Analysis;
3. Package [ampri](https://cran.r-project.org/web/packages/ampir/index.html): Predict antimicrobial peptides;
4. Package [epitopR](https://cran.r-project.org/web/packages/epitopR/index.html): Predict Peptide-MHC Binding;
5. Package [CancerGram](https://cran.r-project.org/web/packages/CancerGram/index.html): Predict Anticancer Peptides;
6. Package [signalHsmm](https://cran.r-project.org/web/packages/signalHsmm/index.html): Predicts the presence of signal peptides in eukaryotic protein using hidden semi-Markov models;
7. Package [AntAngioCOOL](https://cran.r-project.org/web/packages/AntAngioCOOL/index.html): Anti-Angiogenic Peptide Prediction;
8. Package [LSPFP](https://cran.r-project.org/web/packages/LSPFP/index.html): Lysate and Secretome Peptide Feature Plotter;
9. Package [helixvis](https://cran.r-project.org/web/packages/helixvis/index.html): Visualize Alpha-Helical Peptide Sequences;
10. Package [prozor](https://cran.r-project.org/web/packages/prozor/index.html): Minimal Protein Set Explaining Peptide Spectrum Matches;
11. Package [RHybridFinder](https://cran.r-project.org/web/packages/RHybridFinder/index.html): Identification of Hybrid Peptides in Immunopeptidomic Analyses;
12. Package [protag](https://cran.r-project.org/web/packages/protag/index.html): Search Tagged Peptides & Draw Highlighted Mass Spectra;

## DataBases
1. Package [UniprotR](https://cran.r-project.org/web/packages/UniprotR/index.html): Retrieving Information of Proteins from Uniprot;

There are a few more missing. There may be some overlap with Bioconductor: it may be possible to create meaningful links to Bioconductor Task Views (and add the packges there if needed).

## Algorithms
Algorithms in proteomics/genomics may also benefit from:
  - see "Patricia trie" for details on the trie data structure;
1. Package [AhoCorasickTrie](https://cran.r-project.org/web/packages/AhoCorasickTrie/index.html): Fast Searching for Multiple Keywords in Multiple Texts;
2. Package [triebeard](https://cran.r-project.org/web/packages/triebeard/index.html): Radix Trees in Rcpp;

**Comment by k-m-m** [comment]
Thank you for these suggestions.  In my view these peptide and protein-related packages are a better fit for the Omics task view --- https://cran.r-project.org/web/views/Omics.html -- that has a focus more on biochemistry.
