### ISSUE TITLE
Package 'ISRaD' has been archived on CRAN for more than 60 days

### ISSUE THREAD

**Issue by statmath-it** [cran-task-views/ChemPhys#20]
Package [ISRaD](https://CRAN.R-project.org/package=ISRaD) is currently listed in CRAN Task View [ChemPhys](https://CRAN.R-project.org/view=ChemPhys) but the package has actually been archived for more than 60 days on CRAN.  Often this indicates that the package is currently not sufficiently actively maintained and should be excluded from the task view.

Alternatively, you might also consider reaching out to the authors of the package and encourage (or even help) them to bring the package back to CRAN.

In any case, the situation should be resolved in the next four weeks. If the package does not seem to be brought back to CRAN, please exclude it from the task view.

**Comment by zeileis** [comment]
The package is still archived on CRAN so it's probably time to remove it from the task view. Or do you think it is still worth trying to reach out to the maintainer? (For our recommendations how to deal with this, see the new [maintenance guidelines](https://github.com/cran-task-views/ctv/blob/main/Maintenance.md).)

**Comment by k-m-m** [comment]
I have been in touch with him - he expects the new version to be back on CRAN in a week or so.  I will check back with him next week.

**Comment by zeileis** [comment]
Perfect, thanks, Kate!

**Comment by k-m-m** [comment]
CRAN is on vacation; the maintainer now expects ISRaD to be back on CRAN around Aug. 7.
